server:
  port: 8080

spring:
  datasource:
    username: root
    password: Nesquik943
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    properties:
      hibernate:

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

indexing-settings:
  sites:
    - url: https://www.svetlica-seliger.ru
      name: Svetlica-Seliger
    - url: https://sendel.ru
      name: Sendel.ru
    - url: https://tvoy-seliger.com
      name: Tvoy-Seliger.ru

connection-settings:
  userAgent: "AM_SearchBot"
  referer: "http://www.google.com"





